name: BuildJet
on:
  push:

jobs:
  push-image:
    name: Build
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: build-api-image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64